baseURL = "https://oiec-inf.org/"
languageCode = "es"
title = "OIEC"
author = "Adrian Delgado"

pluralizelisttitles = false
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

pygmentsCodefences = true
pygmentsStyle = "vs"

[params]
  description = "Página oficial de la Olimpiada Informática Ecuatoriana"
  images = ["oiec-logo.png"]
  title = "Olimpiada Informática Ecuatoriana - OIEC"

[build]
  writeStats = true