baseURL = "https://oiec-inf.netlify.app/"
languageCode = "es"
title = "OIEC"
author = "Adrian Delgado"

summaryLength = 15
paginate = 6
pluralizelisttitles = false
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true
canonifyURLs = true

pygmentsCodefences = true
pygmentsStyle = "vs"

[taxonomies]
  category = "categories"
  tag = "tags"
  2021 = "2021"

[permalinks]
  noticias = "/:year/:month/:slug/"
  page = "/:slug/"

[params]
  description = "Página oficial de la Olimpiada Informática Ecuatoriana"
  images = ["oiec-logo.png"]
  title = "Olimpiada Informática Ecuatoriana - OIEC"

[build]
  writeStats = true